### ISSUE TITLE
Define `indexAllocator` in the specification

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/vc-api#485]
The specification currently does not define the `indexAllocator` property on the `/credentials/status`. It needs to be defined in the specification.

A PR needs to be raised that says that when the list is created `indexAllocator` is used, and then must be re-used when status is updated. Status service manages status lists with index allocators.

**Comment by kezike** [comment]
This issue seems to be redundant with Issue #594, which is currently addressed by open PR #625. Permission to close this issue @msporny?

**Comment by msporny** [comment]
Works for me, though I was tracking it for @dlongley, so he's probably the one to ask. We should close the issue once the PR is merged (you usually don't want to close issues before PRs are merged because sometimes the PR is aborted and the issue remains).
